version: '2'
services:
  db:
    image: mysql
    container_name: crmka_db
    restart: unless-stopped
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/logs:/var/log/mysql/
      - ./docker/mysql/dump:/docker-entrypoint-initdb.d
    command: --sql_mode=""
    ports:
      - "${MYSQL_PORT}:3306"
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
      - backend
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        DOCKER_PHP_VERSION: '7.4'
        DOCKER_MONGODB_VERSION: 'mongodb-1.20.1'
        DOCKER_REDIS_VERSION: 'redis-6.1.0'
        DOCKER_PHP_ENABLE_XDEBUG: ${DOCKER_PHP_ENABLE_XDEBUG}
        DOCKER_PHP_XDEBUG_VERSION: ${DOCKER_PHP_XDEBUG_VERSION}
        TZ: ${WORKSPACE_TIMEZONE}
    working_dir: /var/www/crmka.local
    container_name: crmka_php
    volumes:
      - .:/var/www/crmka.local
      - ./docker/php/conf/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "${PHP_PORT}:9000"
    networks:
      - backend
  nginx:
    image: nginx:stable-alpine
    container_name: crmka_nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - .:/var/www/crmka.local
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx/
    depends_on:
      - php
      - db
    networks:
      backend:
networks:
  backend:
