version: '2'
services:
  db:
    image: mysql
    container_name: db
    restart: unless-stopped
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/logs:/var/log/mysql/
      - ./docker/mysql/dump:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
      - backend
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        DOCKER_PHP_VERSION: '7.4'
        DOCKER_PHP_ENABLE_XDEBUG: ${DOCKER_PHP_ENABLE_XDEBUG}
        DOCKER_PHP_XDEBUG_VERSION: ${DOCKER_PHP_XDEBUG_VERSION}
        TZ: ${WORKSPACE_TIMEZONE}
    working_dir: /var/www
    container_name: php
    volumes:
      - .:/var/www
      - ./docker/php/conf/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "${PHP_PORT}:9000"
    networks:
      - backend
networks:
  backend:
