GET {{url}}/chat-members?model_type=object&page=11
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###

GET {{url}}/chat-members/43612
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###