GET {{url}}/chat-member-messages
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###

POST {{url}}/chat-member-messages
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "message": "IDI NA HUI",
  "to_chat_member_id": 54158
}

###

POST {{url}}/chat-member-messages/create-task/5
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "user_id": 3,
  "message": "SUKA",
  "status": 1
}

###

POST {{url}}/tasks
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "user_id": 3,
  "message": "SUKA",
  "status": 1
}