GET {{url}}/chat-member-messages?id=5
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###

GET {{url}}/chat-member-messages?to_chat_member_id=43593&from_chat_member_id=46941
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###

POST {{url}}/chat-member-messages
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "message": "ANAL JOSKI",
  "to_chat_member_id": 43593
}

###

POST {{url}}/chat-member-messages/create-task/5
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "user_id": 3,
  "message": "ANAL",
  "status": 1
}

###

POST {{url}}/tasks
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "user_id": 3,
  "message": "SUKA",
  "status": 1
}