GET {{url}}/tasks
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

###

POST {{url}}/tasks
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "user_id": 3,
  "message": "SUKA",
  "status": 1
}
###

PUT {{url}}/tasks/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "user_id": 3,
  "message": "ANAL2",
  "status": 1,
  "created_by_type": "user",
  "created_by_id": 3
}
###